### ISSUE TITLE
 Jellyfin Display Language 

### ISSUE THREAD

**Issue by ks0002544** [Hetsh/docker-jellyfin#3] opened 2023-11-19 09:21 UTC
I am using QNAP Container Station for Jellyfin runnig. In general everything works fine except language changing doesnt work. I am choosing my native language but english still exist. How can I change display language?

**Comment by Hetsh** [comment] 2023-11-29 18:56
If you change the language in Settings > Display > Display language, save the settings and then refresh the page, the language changes. I usually have it set to "Auto", but I also tested it with english. Everything works for me, I'm afraid I can't reproduce your error.

**Comment by ks0002544** [comment] 2023-11-29 19:35
Can you try the following to change the language
Dashboard -> General -> Settings (Preferred display language)

**Comment by Hetsh** [comment] 2023-12-02 08:52
Ah, yes I can confirm that setting the Language under Dashboard -> General -> Settings (Preferred display language) also does not have any effect for me. I am not sure if this is by design, a Jellyfin issue or an issue with my docker image. I suggest changing the language via Settings > Display > Display language as workaround.

**Comment by Hetsh** [comment] 2023-12-17 16:22
I just checked the official Docker image and it behaves the same. So I will close this issue and suggest you to open a new one in the Jellyfin repository.

**Closed as completed by Hetsh** 2023-12-17 16:22 UTC
